# Generated by Django 4.0.3 on 2022-03-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.BooleanField(default=True, verbose_name='Заметка в календаре'),
        ),
    ]
